# Generated by Django 6.0.5 on 2026-05-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
