# Generated by Django 6.0.5 on 2026-06-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField()),
                ('html', models.TextField(blank=True, default='')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(choices=[('save', 'Save'), ('restore', 'Restore'), ('manual', 'Manual')], default='save', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='builder.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', '-created_at'], name='builder_sit_site_id_b30dd3_idx')],
            },
        ),
    ]
