# Generated by Django 6.0.5 on 2026-06-24 10:10

import math

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_hot_score(apps, schema_editor):
    """Seed hot_score for existing sites so the Explore feed ranks them right
    away (new saves recompute it going forward)."""
    Site = apps.get_model('builder', 'Site')
    Favorite = apps.get_model('builder', 'Favorite')
    for site in Site.objects.all():
        fav = Favorite.objects.filter(site=site).count()
        popularity = (site.view_count or 0) + 5 * fav
        created = site.created_at or timezone.now()
        site.hot_score = math.log10(max(popularity, 1)) + created.timestamp() / 45000.0
        site.save(update_fields=['hot_score'])


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_remove_site_favorite_site_view_count_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('business', 'Business'), ('blog', 'Blog'), ('landing', 'Landing'), ('shop', 'Shop'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='hot_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='site',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['published', '-hot_score'], name='builder_sit_publish_0d6337_idx'),
        ),
        migrations.RunPython(backfill_hot_score, migrations.RunPython.noop),
    ]
