# Generated by Django 6.0.5 on 2026-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_oauth_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('recaptcha_site_key', models.CharField(blank=True, default='', max_length=255)),
                ('recaptcha_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('email_host_password', models.CharField(blank=True, default='', max_length=255)),
                ('email_host', models.CharField(blank=True, default='', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_host_user', models.CharField(blank=True, default='', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.CharField(blank=True, default='', max_length=255)),
                ('frontend_url', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
