# Generated by Django 6.0.5 on 2026-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteversion',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
