# Generated by Django 6.0.5 on 2026-08-04 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_profile_github_profile_headline_profile_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(choices=[('portfolio', 'Portfolio'), ('business', 'Business'), ('blog', 'Blog'), ('landing', 'Landing'), ('shop', 'Shop'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('html', models.TextField()),
                ('css', models.TextField(blank=True, default='')),
                ('fonts', models.JSONField(blank=True, default=list)),
                ('policy', models.CharField(choices=[('static', 'Static — markup and styles only'), ('interactive', 'Interactive — may run scripts (moderated)')], default='static', max_length=12)),
                ('natural_width', models.PositiveIntegerField(default=0)),
                ('natural_height', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('removed', 'Removed by moderation'), ('withdrawn', 'Withdrawn by the author')], db_index=True, default='published', max_length=10)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('hot_score', models.FloatField(db_index=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_components', to=settings.AUTH_USER_MODEL)),
                ('source_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_components', to='builder.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedComponentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('inappropriate', 'Inappropriate or offensive'), ('copyright', 'Copyright or impersonation'), ('malware', 'Malicious or phishing'), ('other', 'Other')], default='other', max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='builder.sharedcomponent')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharedcomponent',
            index=models.Index(fields=['status', '-hot_score'], name='builder_sha_status_376f29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedcomponentreport',
            unique_together={('component', 'reporter')},
        ),
    ]
