# Generated by Django 6.0.5 on 2026-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_sharedcomponent_sharedcomponentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcomponent',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public — anyone can take it'), ('private', 'Private — only you')], db_index=True, default='public', max_length=8),
        ),
    ]
