# Generated by Django 6.0.5 on 2026-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_sharedcomponent_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='moderation_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
