# Generated by Django 6.0.5 on 2026-09-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_site_moderation_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.SlugField(blank=True, default='', max_length=140)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('html', models.TextField(blank=True, default='')),
                ('no_index', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_pages', to='builder.site')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'unique_together': {('site', 'path')},
            },
        ),
    ]
