# Generated by Django 6.0.5 on 2026-09-22 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_profile_is_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='share_mode',
            field=models.CharField(choices=[('off', 'Not shared'), ('link', 'Anyone with the link'), ('people', 'Only invited people')], default='link', max_length=8),
        ),
        migrations.CreateModel(
            name='SiteViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='builder.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['invited_at'],
                'unique_together': {('site', 'user')},
            },
        ),
    ]
