# Generated by Django 6.0.5 on 2026-09-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_site_share_mode_siteviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='pinned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
