const TEMPLATE_TEXT_TR = {
  Home: 'Ana Sayfa',
  About: 'Hakkında',
  Elsewhere: 'Diğer bağlantılar',
  Work: 'Çalışmalar',
  Services: 'Hizmetler',
  Menu: 'Menü',
  Visit: 'Ziyaret',
  Product: 'Ürün',
  Features: 'Özellikler',
  Gallery: 'Galeri',
  Subscribe: 'Abone ol',
  Schedule: 'Program',
  RSVP: 'Katılım bildir',
  Shop: 'Mağaza',
  Experience: 'Deneyim',
  Skills: 'Beceriler',
  Pricing: 'Fiyatlandırma',
  Reviews: 'Yorumlar',
  Articles: 'Yazılar',
  Venue: 'Mekân',
  Booking: 'Rezervasyon',
  'Our story': 'Hikâyemiz',
  'Work with me': 'Birlikte çalışalım',
  'Get in touch': 'İletişime geçin',
  'Start free': 'Ücretsiz başla',
  Download: 'İndir',
  'Get a quote': 'Teklif alın',
  'Start a project': 'Projeyi başlat',
  'See results': 'Sonuçları görün',
  'What we do': 'Neler yapıyoruz',
  'Case studies': 'Vaka çalışmaları',
  'Recent results': 'Son sonuçlar',
  'Tell us about your project': 'Projenizi bize anlatın',
  'See the menu': 'Menüyü görün',
  'What we serve': 'Neler sunuyoruz',
  Breakfast: 'Kahvaltı',
  Lunch: 'Öğle yemeği',
  'Coffee & more': 'Kahve ve daha fazlası',
  'Hours & location': 'Saatler ve konum',
  'Open in Maps': 'Haritada aç',
  'Private events & catering': 'Özel etkinlikler ve catering',
  'Ask about dates': 'Tarihleri sorun',
  'Book a shoot': 'Çekim ayırtın',
  'View gallery': 'Galeriyi görün',
  'Check dates': 'Tarihleri kontrol edin',
  'Recent frames': 'Son kareler',
  'Check availability': 'Uygunluğu kontrol edin',
  'Notes from the workshop.': 'Atölyeden notlar.',
  Engineering: 'Mühendislik',
  Design: 'Tasarım',
  Writing: 'Yazı',
  'One essay a month': 'Ayda bir yazı',
  'Subscribe by email': 'E-posta ile abone olun',
  'See the schedule': 'Programı görün',
  'The day': 'Günün programı',
  'Guests arrive': 'Misafirlerin gelişi',
  Ceremony: 'Tören',
  Dinner: 'Akşam yemeği',
  Party: 'Kutlama',
  Where: 'Nerede',
  'The venue': 'Mekân',
  'Will you join us?': 'Bize katılacak mısınız?',
  'RSVP by email': 'E-posta ile katılım bildirin',
  'Shop now': 'Şimdi alışveriş yap',
  'Browse the shop': 'Mağazayı gezin',
  Bestsellers: 'Çok satanlar',
  'Why small batches': 'Neden küçük üretim?',
  'Questions about an order?': 'Sipariş hakkında sorunuz mu var?',
  'Built with care.': 'Özenle hazırlandı.',
  'All rights reserved.': 'Tüm hakları saklıdır.',
  Profile: 'Profil',
  Education: 'Eğitim',
  Contact: 'İletişim',
  Career: 'Kariyer',
  Toolkit: 'Araçlar',
  'Senior Product Designer': 'Kıdemli Ürün Tasarımcısı',
  'Product Designer': 'Ürün Tasarımcısı',
  'UI Designer': 'Arayüz Tasarımcısı',
  'B.A. Visual Design': 'Görsel Tasarım Lisansı',
  'Product strategy': 'Ürün stratejisi',
  'Design systems': 'Tasarım sistemleri',
  Prototyping: 'Prototipleme',
  'User research': 'Kullanıcı araştırması',
  'Open to new roles': 'Yeni fırsatlara açık',
  'Years of experience': 'Yıllık deneyim',
  'Projects shipped': 'Tamamlanan proje',
  'Teams supported': 'Desteklenen ekip',
  'Skills & education': 'Beceriler ve eğitim',
  'Email me': 'E-posta gönder',
  'Hire me': 'Birlikte çalışalım',
  "Let's work together": 'Birlikte çalışalım',
  'Product designer with 8+ years crafting clear, responsive interfaces. I care about systems, typography, and shipping work that lasts.': 'Net ve duyarlı arayüzler tasarlayan 8+ yıllık deneyime sahip ürün tasarımcısıyım. Sistemlere, tipografiye ve kalıcı işler üretmeye önem veriyorum.',
  'Led the redesign of the core product, improving activation by 28%. Built and maintained the design system used across 6 teams.': 'Ana ürünün yeniden tasarımını yöneterek aktivasyonu %28 artırdım. Altı ekipte kullanılan tasarım sistemini kurup geliştirdim.',
  'Owned end-to-end design for the mobile app from research to ship. Partnered closely with engineering on a fluid, responsive UI.': 'Mobil uygulamanın araştırmadan yayına kadar uçtan uca tasarımını üstlendim. Akıcı ve duyarlı bir arayüz için mühendislik ekibiyle yakın çalıştım.',
  'Designed marketing pages and interface components. Introduced a reusable layout grid that cut handoff time in half.': 'Pazarlama sayfaları ve arayüz bileşenleri tasarladım. Teslim süresini yarıya indiren yeniden kullanılabilir bir yerleşim sistemi geliştirdim.',
  'Graduated with honors; thesis on accessible interface patterns.': 'Erişilebilir arayüz kalıpları üzerine tezle onur derecesiyle mezun oldum.',
  'A track record of shipping design that moves real product metrics.': 'Gerçek ürün metriklerini iyileştiren tasarımlar üretme deneyimi.',
  'Also: conference speaker, design-systems meetup organizer.': 'Ayrıca konferans konuşmacısı ve tasarım sistemleri buluşması düzenleyicisi.',
  'Tell me about your team and what you are building — I usually reply within one business day.': 'Ekibinizi ve ne geliştirdiğinizi anlatın; genellikle bir iş günü içinde yanıt veririm.',
  'Product designer crafting clear, responsive interfaces.': 'Net ve duyarlı arayüzler tasarlayan ürün tasarımcısı.',
  Portfolio: 'Portfolyo',
  'Selected work': 'Seçili çalışmalar',
  'Designer & developer': 'Tasarımcı ve geliştirici',
  'Work that ships,': 'Yalnızca güzel değil,',
  'not just shines.': 'yayına hazır işler.',
  'Selected projects from eight years of building products, brands, and websites for teams that care about craft.': 'Ürüne önem veren ekipler için ürün, marka ve web sitesi geliştirdiğim sekiz yıldan seçili projeler.',
  'See the work': 'Çalışmaları gör',
  'Six projects that show range: product, web, mobile, and brand.': 'Ürün, web, mobil ve marka alanlarındaki çeşitliliği gösteren altı proje.',
  'Design with an engineering brain': 'Mühendislik bakışıyla tasarım',
  'I prototype in code, obsess over type and spacing, and measure outcomes after launch. Teams keep me around because handoff is painless and the details survive production.': 'Kodla prototip üretir, tipografi ve aralıklara özen gösterir, sonuçları yayından sonra ölçerim. Sorunsuz teslim ve üretimde korunan ayrıntılar için ekiplerle uzun süre çalışırım.',
  Projects: 'Projeler',
  Industries: 'Sektör',
  'Have a project in mind?': 'Aklınızda bir proje mi var?',
  'Tell me what you are building and where you are stuck — I reply within one business day.': 'Ne geliştirdiğinizi ve nerede zorlandığınızı anlatın; bir iş günü içinde yanıt veririm.',
  'Independent designer & developer. Available for select projects.': 'Bağımsız tasarımcı ve geliştirici. Seçili projeler için müsait.',
  'Designer making calm, usable software.': 'Sade ve kullanışlı yazılımlar tasarlayan bir tasarımcı.',
  'A plain page, on purpose. The work below speaks for itself.': 'Bilinçli olarak sade bir sayfa. Aşağıdaki çalışmalar kendini anlatıyor.',
  'Want the full case studies?': 'Tüm vaka çalışmalarını görmek ister misiniz?',
  Web: 'Web',
  Mobile: 'Mobil',
  Brand: 'Marka',
  Systems: 'Sistemler',
  FAQ: 'SSS',
  'Now in public beta': 'Şimdi herkese açık beta sürümünde',
  'Ship your product site': 'Ürün sitenizi',
  'in an afternoon.': 'bir öğleden sonra yayınlayın.',
  'See features': 'Özellikleri gör',
  'Teams on board': 'Kullanan ekip',
  Uptime: 'Çalışma süresi',
  'Average rating': 'Ortalama puan',
  'Everything you actually need': 'Gerçekten ihtiyacınız olan her şey',
  'No bloat. Three things, done extremely well.': 'Gereksiz kalabalık yok. Üç temel iş, son derece iyi yapılır.',
  'Fast by default': 'Varsayılan olarak hızlı',
  'Static pages served from the edge. 100/100 performance without tuning.': 'Uç sunuculardan sunulan statik sayfalar. Ayar gerektirmeden 100/100 performans.',
  'Secure forms': 'Güvenli formlar',
  'Spam-filtered submissions delivered to your inbox or webhook.': 'Spam filtresinden geçen gönderimler gelen kutunuza veya webhook adresinize iletilir.',
  'Private analytics': 'Gizlilik odaklı analizler',
  'Cookieless metrics your legal team will actually approve.': 'Hukuk ekibinizin onaylayacağı çerezsiz metrikler.',
  'Simple, honest pricing': 'Basit ve şeffaf fiyatlandırma',
  'Start free. Upgrade when you outgrow it.': 'Ücretsiz başlayın, ihtiyaçlarınız büyüdüğünde yükseltin.',
  Starter: 'Başlangıç',
  Pro: 'Profesyonel',
  Team: 'Ekip',
  'Most popular': 'En popüler',
  'Community support': 'Topluluk desteği',
  'Custom domain': 'Özel alan adı',
  'No badge': 'Rozet yok',
  'Priority support': 'Öncelikli destek',
  'Unlimited sites': 'Sınırsız site',
  'Roles & permissions': 'Roller ve izinler',
  'Audit log': 'Denetim günlüğü',
  'Questions, answered': 'Sorular ve yanıtları',
  'Can I use my own domain?': 'Kendi alan adımı kullanabilir miyim?',
  'Yes — Pro and Team plans connect any domain with automatic SSL.': 'Evet. Profesyonel ve Ekip planları otomatik SSL ile her alan adına bağlanabilir.',
  'Do you offer refunds?': 'Para iadesi sunuyor musunuz?',
  'Full refund within 30 days, no questions asked.': 'İlk 30 gün içinde koşulsuz tam iade sunuyoruz.',
  'Can I export my site?': 'Sitemi dışa aktarabilir miyim?',
  'Always. Your content is yours; export clean HTML at any time.': 'Her zaman. İçeriğiniz size aittir; istediğiniz zaman temiz HTML olarak dışa aktarabilirsiniz.',
  'Ready to ship?': 'Yayınlamaya hazır mısınız?',
  'Join 12,000 teams building faster sites with less hassle.': 'Daha hızlı ve kolay site geliştiren 12.000 ekibe katılın.',
  'Start free today': 'Bugün ücretsiz başlayın',
  'The fastest way from idea to a live product site.': 'Fikirden yayındaki ürün sitesine giden en hızlı yol.',
  'Get the app': 'Uygulamayı edin',
  'iOS & Android': 'iOS ve Android',
  'Your day,': 'Gününüz',
  'finally under control.': 'artık kontrol altında.',
  'Download free': 'Ücretsiz indir',
  'How it works': 'Nasıl çalışır?',
  'Built for focus': 'Odaklanmak için geliştirildi',
  'Smart planning': 'Akıllı planlama',
  'Drop tasks in; the schedule builds itself around your meetings.': 'Görevleri ekleyin; program toplantılarınıza göre kendini oluştursun.',
  'Focus mode': 'Odak modu',
  'One tap silences everything that is not the current task.': 'Tek dokunuş, mevcut görev dışındaki tüm dikkat dağıtıcıları susturur.',
  'Weekly review': 'Haftalık değerlendirme',
  'See where the hours actually went — and fix next week.': 'Saatlerin nereye gittiğini görün ve gelecek haftayı iyileştirin.',
  'Loved by busy people': 'Yoğun çalışanların favorisi',
  '“Deleted three other apps”': '“Diğer üç uygulamayı sildim”',
  '— Maya R., product manager. The planner I always wanted.': '— Maya R., ürün yöneticisi. Her zaman aradığım planlayıcı.',
  '“My evenings are back”': '“Akşamlarımı geri kazandım”',
  '— Jonas K., engineer. The focus mode alone is worth it.': '— Jonas K., mühendis. Yalnızca odak modu bile yeterli.',
  '“Simple, not simplistic”': '“Sade ama basit değil”',
  '— Aylin T., founder. Powerful without the clutter.': '— Aylin T., kurucu. Kalabalık olmadan güçlü.',
  'On the App Store and Google Play. Pro upgrade when you are ready.': 'App Store ve Google Play’de. Hazır olduğunuzda Profesyonel sürüme geçin.',
  'Download now': 'Şimdi indir',
  'The calm planner for busy weeks.': 'Yoğun haftalar için sakin bir planlayıcı.',
  'Design & engineering studio': 'Tasarım ve mühendislik stüdyosu',
  'Websites that earn': 'Değer üreten',
  'their keep.': 'web siteleri.',
  'We design, build, and maintain fast marketing sites for B2B teams — measured by pipeline, not pixels.': 'B2B ekipleri için hızlı pazarlama siteleri tasarlıyor, geliştiriyor ve sürdürüyoruz; başarıyı pikselle değil sonuçlarla ölçüyoruz.',
  'Sites launched': 'Yayınlanan site',
  'Avg. conversion lift': 'Ort. dönüşüm artışı',
  'Typical delivery': 'Tipik teslimat',
  'Three engagements, fixed scope, fixed price.': 'Üç hizmet modeli, net kapsam ve sabit fiyat.',
  'Site sprint': 'Site sprinti',
  'A full marketing site designed and live in 14 days.': 'Eksiksiz bir pazarlama sitesi 14 günde tasarlanır ve yayınlanır.',
  'Component libraries your team can actually maintain.': 'Ekibinizin gerçekten sürdürebileceği bileşen kütüphaneleri.',
  'Growth retainers': 'Büyüme desteği',
  'Continuous experiments: landing pages, A/B tests, SEO.': 'Sürekli deneyler: açılış sayfaları, A/B testleri ve SEO.',
  'Send a short brief — we respond with a plan and a fixed quote within 48 hours.': 'Kısa bir özet gönderin; 48 saat içinde plan ve sabit fiyat teklifiyle yanıtlayalım.',
  'A small studio with senior people only. No account managers.': 'Yalnızca deneyimli uzmanlardan oluşan küçük bir stüdyo. Aracı hesap yöneticisi yok.',
  'Find us': 'Bizi bulun',
  'Neighbourhood café · est. 2019': 'Mahalle kafesi · 2019’dan beri',
  'Good coffee.': 'İyi kahve.',
  'Honest food.': 'Dürüst yemek.',
  'Everything made in-house every morning: bread, cakes, and the best flat white on the street.': 'Ekmek, kek ve sokağın en iyi flat white’ı dahil her şey her sabah mutfağımızda hazırlanır.',
  'Seasonal, local, and changing often — this is today.': 'Mevsimlik, yerel ve sık değişen bugünkü menümüz.',
  'Sourdough & whipped butter': 'Ekşi mayalı ekmek ve çırpılmış tereyağı',
  'Shakshuka, herbs, warm bread': 'Şakşuka, otlar ve sıcak ekmek',
  'Granola, yogurt, berries': 'Granola, yoğurt ve orman meyveleri',
  'Roast cauliflower bowl': 'Fırın karnabahar kasesi',
  'Chicken schnitzel sandwich': 'Tavuk şinitzel sandviç',
  'Seasonal soup & bread': 'Mevsim çorbası ve ekmek',
  'Flat white': 'Flat white',
  'Filter — single origin': 'Filtre kahve — tek köken',
  'House lemonade': 'Ev yapımı limonata',
  'Mon–Fri': 'Pzt–Cum',
  'Sat–Sun': 'Cmt–Paz',
  'Kadıköy, Moda Cd. 42 — two minutes from the ferry.': 'Kadıköy, Moda Cd. 42 — vapura iki dakika.',
  'We host breakfasts, book clubs, and small launches up to 30 people.': '30 kişiye kadar kahvaltı, kitap kulübü ve küçük lansmanlara ev sahipliği yapıyoruz.',
  'Good coffee, honest food, friendly people.': 'İyi kahve, dürüst yemek ve güler yüzlü insanlar.',
  'Photographer · weddings & portraits': 'Fotoğrafçı · düğün ve portre',
  'Light, caught': 'Doğru anda',
  'at the right second.': 'yakalanan ışık.',
  'Editorial photography for people who hate posing. Natural, calm, and a little cinematic.': 'Poz vermeyi sevmeyenler için editoryal fotoğrafçılık. Doğal, sakin ve biraz sinematik.',
  'Hi, I am behind the camera': 'Merhaba, kameranın arkasındaki kişiyim',
  'Ten years, four hundred weddings, one rule: real moments beat staged ones. I shoot quietly, edit warmly, and deliver fast.': 'On yıl, dört yüz düğün ve tek kural: gerçek anlar kurgulanmış olanlardan değerlidir. Sessizce çeker, sıcak tonlarda düzenler ve hızlı teslim ederim.',
  '2026 dates are open': '2026 tarihleri açık',
  'Tell me about your day — date, place, and what matters most to you.': 'Gününüzü; tarihi, yeri ve sizin için en önemli ayrıntıları anlatın.',
  'Editorial photography, weddings & portraits.': 'Editoryal fotoğrafçılık, düğün ve portre.',
  'A blog about building software': 'Yazılım geliştirme üzerine bir blog',
  'Essays on product, design, and engineering — one a month, no filler.': 'Ürün, tasarım ve mühendislik üzerine ayda bir, dolgu içermeyen yazılar.',
  'The case for boring technology': 'Sıkıcı teknolojinin haklılığı',
  'Why our stack got simpler every year — and shipping got faster.': 'Teknoloji yığınımız neden her yıl sadeleşirken yayınlama hızımız arttı?',
  'Designing for the third read': 'Üçüncü okuma için tasarlamak',
  'Interfaces reveal themselves in layers. Plan all three.': 'Arayüzler katmanlar hâlinde kendini gösterir. Üçünü de planlayın.',
  'What I learned from 100 user calls': '100 kullanıcı görüşmesinden öğrendiklerim',
  'Patterns only show up after call forty. Keep going.': 'Kalıplar ancak kırkıncı görüşmeden sonra belirginleşir. Devam edin.',
  'Writing docs people actually read': 'İnsanların gerçekten okuduğu dokümanlar yazmak',
  'Structure beats prose. Examples beat structure.': 'Yapı anlatımdan, örnekler yapıdan güçlüdür.',
  'Jun 2026': 'Haz 2026',
  'May 2026': 'May 2026',
  'Apr 2026': 'Nis 2026',
  'Mar 2026': 'Mar 2026',
  'No spam, no growth hacks — just the writing. Unsubscribe anytime.': 'Spam ve büyüme hilesi yok; yalnızca yazılar. İstediğiniz zaman abonelikten çıkın.',
  'Essays on product, design, and engineering.': 'Ürün, tasarım ve mühendislik üzerine yazılar.',
  'Saturday · 12 September 2026 · Istanbul': 'Cumartesi · 12 Eylül 2026 · İstanbul',
  "We're getting": 'Evleniyoruz.',
  'married.': 'Hayatlarımızı birleştiriyoruz.',
  'And it would mean the world to celebrate with you. Here is everything you need for the day.': 'Bu günü sizinle kutlamak bizim için çok değerli. Günle ilgili ihtiyacınız olan her şey burada.',
  'RSVP now': 'Şimdi katılım bildir',
  'Welcome drinks on the terrace.': 'Terasta karşılama içecekleri.',
  'Short and sweet — bring sunglasses.': 'Kısa ve güzel; güneş gözlüğünüzü getirin.',
  'Long tables, family style, lots of toasts.': 'Uzun masalar, aile usulü servis ve bolca kutlama.',
  'First dance, then everyone dances. Until late.': 'İlk dansın ardından herkes gece geç saatlere kadar dans edecek.',
  'Esma Sultan Mansion, Ortaköy — on the water, under the bridge. Dress code: summer formal. Parking is limited; taxis are easy.': 'Esma Sultan Yalısı, Ortaköy — denizin kıyısında, köprünün altında. Kıyafet: yazlık resmî. Otopark sınırlı; taksi kullanımı kolay.',
  'Please reply by 1 August — and tell us about any dietary needs.': 'Lütfen 1 Ağustos’a kadar yanıt verin ve özel beslenme ihtiyaçlarınızı belirtin.',
  'With love — see you in September.': 'Sevgiyle — Eylül’de görüşmek üzere.',
  'Small-batch goods · free EU shipping over €60': 'Küçük üretim · €60 üzeri AB’ye ücretsiz kargo',
  'Made slowly.': 'Yavaş üretildi.',
  'Made to last.': 'Uzun ömürlü tasarlandı.',
  'Homeware from small European workshops — every piece traceable to the person who made it.': 'Küçük Avrupa atölyelerinden ev ürünleri; her parçanın üreticisi belli.',
  'Canvas tote — natural': 'Kanvas çanta — doğal',
  'Enamel mug — forest': 'Emaye kupa — orman',
  'Linen apron — rust': 'Keten önlük — pas rengi',
  'Beeswax candle set': 'Balmumu mum seti',
  'Ceramic pour-over': 'Seramik pour-over',
  'Wool throw — oat': 'Yün örtü — yulaf',
  'We visit every workshop, pay fairly, and stock little. When something sells out, it comes back when it is ready — not before.': 'Her atölyeyi ziyaret eder, adil ödeme yapar ve az stok tutarız. Tükenen ürün ancak yeniden hazır olduğunda geri gelir.',
  'We answer every email within a day — usually faster.': 'Her e-postayı bir gün içinde, çoğunlukla daha hızlı yanıtlarız.',
  'Small-batch homeware from European workshops.': 'Avrupa atölyelerinden küçük üretim ev ürünleri.',
  'Latest podcast episode': 'Son podcast bölümü',
  'Newsletter — one email a week': 'Bülten — haftada bir e-posta',
  'Tools I use daily': 'Her gün kullandığım araçlar',
  'Book a 15-min call': '15 dakikalık görüşme ayarla',
  'Maker, writer, and occasional podcaster. Everything I do, one tap away.': 'Üretici, yazar ve zaman zaman podcast yayıncısı. Yaptığım her şey tek dokunuş uzağınızda.',
  'Open menu': 'Menüyü aç',
  'Decorative visual': 'Dekoratif görsel',
  Photograph: 'Fotoğraf',
}

const PHRASE_REPLACEMENTS_TR = [
  [' handles the boring parts — hosting, forms, analytics — so your team can focus on the product.', ' barındırma, formlar ve analiz gibi yorucu işleri üstlenir; ekibiniz ürüne odaklanır.'],
  [' turns scattered tasks into one calm timeline. Plan in seconds, focus for hours.', ' dağınık görevleri sakin bir zaman çizelgesinde toplar. Saniyeler içinde planlayın, saatlerce odaklanın.'],
  ['All rights reserved.', 'Tüm hakları saklıdır.'],
  ['Read more', 'Devamını oku'],
  ['Learn more', 'Daha fazla bilgi'],
  ['View project', 'Projeyi görüntüle'],
  ['View work', 'Çalışmaları görüntüle'],
  ['Send a message', 'Mesaj gönder'],
  ['Your email', 'E-posta adresiniz'],
  ['Email address', 'E-posta adresi'],
]

function translateText(value) {
  const raw = String(value || '')
  const leading = raw.match(/^\s*/)?.[0] || ''
  const trailing = raw.match(/\s*$/)?.[0] || ''
  const text = raw.trim()
  if (!text) return raw
  let translated = TEMPLATE_TEXT_TR[text] || text
  for (const [source, target] of PHRASE_REPLACEMENTS_TR) {
    translated = translated.replaceAll(source, target)
  }
  translated = translated
    .replace(/^Why (.+)$/u, 'Neden $1?')
    .replace(/^Get (.+) free$/u, '$1 uygulamasını ücretsiz edinin')
    .replace(/^Choose (.+)$/u, '$1 planını seç')
    .replace(/^Photograph (\d+)$/u, 'Fotoğraf $1')
    .replace(/^(.+) badge$/u, '$1 rozeti')
  return `${leading}${translated}${trailing}`
}

export function localizeTemplateHtml(html, language = 'en') {
  const source = String(html || '')
  if (!source) return source
  if (typeof DOMParser === 'undefined') {
    return source.replace(/<html([^>]*)>/i, `<html$1 lang="${language}">`)
  }
  const doc = new DOMParser().parseFromString(source, 'text/html')
  doc.documentElement.lang = language
  if (language === 'tr') {
    if (doc.title) doc.title = translateText(doc.title)
    const walker = doc.createTreeWalker(doc.body, NodeFilter.SHOW_TEXT)
    let node = walker.nextNode()
    while (node) {
      if (!node.parentElement?.closest('style,script,code,pre')) node.nodeValue = translateText(node.nodeValue)
      node = walker.nextNode()
    }
    doc.body.querySelectorAll('[aria-label], [title], [placeholder]').forEach((element) => {
      for (const attribute of ['aria-label', 'title', 'placeholder']) {
        if (element.hasAttribute(attribute)) {
          element.setAttribute(attribute, translateText(element.getAttribute(attribute)))
        }
      }
    })
  }
  return `<!doctype html>\n${doc.documentElement.outerHTML}`
}
